name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci:lint
      - run: pnpm run ci:compile
      - run: pnpm run ci:test
